---
version: 2
sphinx:
  configuration: doc/conf.py
build:
  os: "ubuntu-24.04"
  apt_packages:
    - libsasl2-dev
    - libldap2-dev
    - libssl-dev
    - libasound2t64
    - libatk-bridge2.0-0t64
    - libatk1.0-0t64
    - libatspi2.0-0t64
    - libcairo2
    - libcups2t64
    - libdbus-1-3
    - libdrm2
    - libgbm1
    - libglib2.0-0t64
    - libnspr4
    - libnss3
    - libpango-1.0-0
    - libx11-6
    - libxcb1
    - libxcomposite1
    - libxdamage1
    - libxext6
    - libxfixes3
    - libxkbcommon0
    - libxrandr2
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - pip install uv
      - uv export --group doc --no-hashes --output-file requirements.txt
    post_install:
      - pip install .[captcha,front,fido,oidc,otp,sms,server]
      - pip install --requirement requirements.txt
      - playwright install chromium
