---
version: 2
sphinx:
  configuration: doc/conf.py
build:
  os: "ubuntu-24.04"
  apt_packages:
    - libsasl2-dev
    - libldap2-dev
    - libssl-dev
    - libasound2t64 # used for playwright firefox
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - pip install uv
      - uv export --group doc --no-hashes --output-file requirements.txt
    post_install:
      - pip install .[front,oidc,otp,sms]
      - pip install --requirement requirements.txt
      - playwright install firefox
