---
version: 2
sphinx:
  configuration: doc/conf.py
build:
  apt_packages:
    - libsasl2-dev
    - libldap2-dev
    - libssl-dev
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
