---
version: 2
sphinx:
  configuration: doc/conf.py
build:
  os: "ubuntu-22.04"
  apt_packages:
    - libsasl2-dev
    - libldap2-dev
    - libssl-dev
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry export --with doc --output requirements.txt
    post_install:
      - pip install --requirement requirements.txt
