SECRET_KEY = "change me before you go in production"
NAME = MyDomain
# LOGO = "https://path/to/your/organization/logo.png"

# If unset, language is detected
LANGUAGE = "en"

[LDAP]
URI = "ldaps://ldap.mydomain.tld"
BIND_USER = "cn=admin,dc=mydomain,dc=tld"
BIND_PW = "admin"
