SECRET_KEY = "change me before you go in production"
NAME = "MyDomain"
# LOGO = "https://path/to/your/organization/logo.png"

# If unset, language is detected
LANGUAGE = "en"

[LDAP]
URI = "ldap://ldap"
ROOT_DN = "dc=mydomain,dc=tld"
BIND_DN = "cn=admin,dc=mydomain,dc=tld"
BIND_PW = "admin"

ADMIN_FILTER = "cn=Jane Doe"
