---
version: "3"

services:
  canaille:
    hostname: canaille.localhost
    build:
      context: ..
      dockerfile: dev/Dockerfile-canaille
    environment:
      - CANAILLE__DATABASE=sql
      - AUTHLIB_INSECURE_TRANSPORT=1
      - FLASK_DEBUG=1
      - CANAILLE_CONFIG=/opt/canaille/conf/canaille.toml
      - FLASK_APP=devapp
    volumes:
      - ../canaille:/opt/canaille/canaille
      - ./conf:/opt/canaille/conf
    ports:
      - 5000:5000

  client1:
    hostname: client1.localhost
    depends_on:
      - canaille
    build:
      context: .
      dockerfile: Dockerfile-client
    environment:
      - FLASK_DEBUG=1
      - CLIENT_CONFIG=/opt/client/conf/client1.cfg
      - FLASK_APP=client
    volumes:
      - ./client:/opt/client/client
      - ./conf:/opt/client/conf
      - ../canaille/static:/opt/canaille/static
    command: --port=5001
    ports:
      - 5001:5001

  client2:
    hostname: client2.localhost
    depends_on:
      - canaille
    build:
      context: .
      dockerfile: Dockerfile-client
    environment:
      - FLASK_DEBUG=1
      - CLIENT_CONFIG=/opt/client/conf/client2.cfg
      - FLASK_APP=client
    volumes:
      - ./client:/opt/client/client
      - ./conf:/opt/client/conf
      - ../canaille/static:/opt/canaille/static
    command: --port=5002
    ports:
      - 5002:5002

  maildump:
    hostname: maildump.localhost
    build:
      context: ..
      dockerfile: dev/Dockerfile-maildump
    ports:
      - 1025:1025
      - 1080:1080
