import enum
import json
from datetime import timedelta

import click
import tomlkit
from flask import current_app
from flask.cli import with_appcontext
from joserfc.jwk import ECKey
from joserfc.jwk import OctKey
from joserfc.jwk import OKPKey
from joserfc.jwk import RSAKey

from canaille.app import models
from canaille.app.commands import with_backendcontext
from canaille.backends import Backend

from .jose import build_client_management_token
from .jose import get_alg_for_key
from .jose import server_jwks


@click.command()
@with_appcontext
@with_backendcontext
def clean():
    """Remove expired tokens and authorization codes."""
    for t in Backend.instance.query(models.Token):
        if t.is_expired():
            Backend.instance.delete(t)

    for a in Backend.instance.query(models.AuthorizationCode):
        if a.is_expired():
            Backend.instance.delete(a)


@click.group()
def jwk():
    """JSON Web Key management."""
    pass


@jwk.group()
def create():
    """JSON Web Key creation."""
    pass


class OutputFormat(enum.Enum):
    JSON = "json"
    TOML = "toml"


def _print_key(key, output_format: OutputFormat):
    """Print key with the selected output format."""
    if output_format == OutputFormat.JSON:
        click.echo(json.dumps(key.as_dict(private=True)))
    else:
        key_as_table = tomlkit.inline_table()
        key_as_table.update(key.as_dict(private=True))
        click.echo(key_as_table.as_string())


@create.command()
@click.option("--size", default=2048, type=int, help="The key size")
@click.option(
    "--format",
    "output_format",
    type=click.Choice(OutputFormat, case_sensitive=False),
    default=OutputFormat.JSON,
    help="Output format",
)
def rsa(size: int, output_format: OutputFormat):
    """Create a RSA JSON Web Key."""
    key = RSAKey.generate_key(size, auto_kid=True)
    _print_key(key, output_format)


@create.command()
@click.option("--size", default=256, type=int, help="The key size")
@click.option(
    "--format",
    "output_format",
    type=click.Choice(OutputFormat, case_sensitive=False),
    default=OutputFormat.JSON,
    help="Output format",
)
def oct(size: int, output_format: OutputFormat):
    """Create a Oct JSON Web Key."""
    key = OctKey.generate_key(size, auto_kid=True)
    _print_key(key, output_format)


@create.command()
@click.option("--crv", default="P-256", type=str, help="The key CRV")
@click.option(
    "--format",
    "output_format",
    type=click.Choice(OutputFormat, case_sensitive=False),
    default=OutputFormat.JSON,
    help="Output format",
)
def ec(crv: str, output_format: OutputFormat):
    """Create a EC JSON Web Key."""
    key = ECKey.generate_key(crv, auto_kid=True)
    _print_key(key, output_format)


@create.command()
@click.option("--crv", default="Ed25519", type=str, help="The key CRV")
@click.option(
    "--format",
    "output_format",
    type=click.Choice(OutputFormat, case_sensitive=False),
    default=OutputFormat.JSON,
    help="Output format",
)
def okp(crv: str, output_format: OutputFormat):
    """Create a OKP JSON Web Key."""
    key = OKPKey.generate_key(crv, auto_kid=True)
    _print_key(key, output_format)


@jwk.command()
@click.argument("kid", required=False)
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["json", "pem"], case_sensitive=False),
    default="json",
    help="Output the key metadata as JSON or the raw public keys as PEM.",
)
@click.option(
    "--active-only",
    is_flag=True,
    default=False,
    help="Only export the active keys instead of the active and inactive ones.",
)
@with_appcontext
def export(kid: str | None, output_format: str, active_only: bool):
    """Export the public part of the server signing keys.

    Without argument, every asymmetric verification key is exported, active and
    inactive by default so tokens signed during a key rotation window can still
    be verified. A single key can be selected by passing its KID.

    The ``json`` format (default) emits the key metadata: kid, signing
    algorithm, usage and key type. The ``pem`` format emits the raw public keys
    in PEM (SubjectPublicKeyInfo) format, suitable for external JWT validators
    that verify Canaille-issued tokens locally without fetching the JWKS
    endpoint.

    Symmetric keys have no public part and are skipped; the private key material
    is never emitted.
    """
    if current_app.extensions.get("canaille_oidc_jwks_autogenerated"):
        raise click.ClickException(
            "ACTIVE_JWKS is not configured. Refusing to export the auto-generated "
            "keys as they change on every restart. Please configure ACTIVE_JWKS first."
        )

    keys = server_jwks(include_inactive=not active_only).keys

    if kid is not None:
        selected = next((key for key in keys if key.kid == kid), None)
        if selected is None:
            raise click.ClickException(f"No key found with kid '{kid}'.")
        if isinstance(selected, OctKey):
            raise click.ClickException(
                f"Key '{kid}' is symmetric and has no public part."
            )
        exported = [selected]

    else:
        exported = []
        for key in keys:
            if isinstance(key, OctKey):
                click.echo(
                    f"Skipping symmetric key {key.kid} as it has no public part.",
                    err=True,
                )
                continue
            exported.append(key)

    exported.sort(key=lambda key: key.kid or "")

    if output_format == "pem":
        click.echo(b"".join(key.as_pem(private=False) for key in exported), nl=False)
        return

    entries = [
        {
            "kid": key.kid,
            "alg": get_alg_for_key(key),
            "use": key.as_dict(private=False).get("use", "sig"),
            "kty": key.key_type,
        }
        for key in exported
    ]
    payload = entries[0] if kid is not None else entries
    click.echo(json.dumps(payload, indent=2, sort_keys=True))


@click.group()
def jwt():
    """Client registration management."""
    pass


@jwt.command()
@click.option("--lifetime", default=86400, type=int, help="Token lifetime in seconds")
@with_appcontext
def registration(lifetime: int):
    """Generate a JWT token for dynamic client registration.

    Creates a JWT token with an auto-generated client_id that can be used
    to register a new OAuth2 client.
    """
    if not current_app.config["SERVER_NAME"]:
        raise click.ClickException(
            "You must define SERVER_NAME to issue tokens from the CLI"
        )

    token = build_client_management_token(
        "client:register", timedelta(seconds=lifetime)
    )
    click.echo(token)


@jwt.command()
@click.argument("client-id", required=True)
@click.option("--lifetime", default=86400, type=int, help="Token lifetime in seconds")
@with_appcontext
def management(client_id: str, lifetime: int):
    """Generate a JWT token for client management.

    Creates a JWT token that can be used to manage an existing OAuth2 client.
    """
    if not current_app.config["SERVER_NAME"]:
        raise click.ClickException(
            "You must define SERVER_NAME to issue tokens from the CLI"
        )

    token = build_client_management_token(
        "client:manage", timedelta(seconds=lifetime), client_id
    )
    click.echo(token)


def register(cli):
    cli.add_command(clean)
    cli.add_command(jwk)
    cli.add_command(jwt)
