"""Ordered relationships.

Revision ID: 1742033764
Revises: 1740765703
Create Date: 2025-03-15 11:16:04.256771

"""

import warnings
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1742033764"
down_revision: str | None = "1740765703"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def number_rows(table, first, second):
    """Fill the index column with the row number of each association."""
    if op.get_bind().dialect.name == "mysql":
        op.execute(f"""
            UPDATE {table} t
            JOIN (
                SELECT {first}, {second}, ROW_NUMBER() OVER (ORDER BY {first}, {second}) as row_num
                FROM {table}
            ) s
            ON t.{first} = s.{first} AND t.{second} = s.{second}
            SET t.`index` = s.row_num;
        """)
        return

    op.execute(f"""
        UPDATE {table}
        SET "index" = s.row_num
        FROM (
            SELECT {first}, {second}, ROW_NUMBER() OVER (ORDER BY {first}, {second}) as row_num
            FROM {table}
        ) s
        WHERE {table}.{first} = s.{first} AND {table}.{second} = s.{second};
    """)


def add_index(table, first, second, autoincrement):
    op.add_column(
        table,
        sa.Column("index", sa.Integer(), autoincrement=autoincrement, nullable=True),
    )
    number_rows(table, first, second)

    # MySQL only accepts AUTO_INCREMENT on keys, and the other databases ignore it.
    if op.get_bind().dialect.name == "mysql":
        return

    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore",
            message="autoincrement and existing_autoincrement only make sense for MySQL",
        )
        with op.batch_alter_table(table) as batch_op:
            batch_op.alter_column(
                "index", existing_type=sa.Integer(), autoincrement=True
            )


def upgrade() -> None:
    add_index("client_audience_association_table", "audience_id", "client_id", "auto")
    add_index("membership_association_table", "user_id", "group_id", True)
    add_index("token_audience_association_table", "token_id", "client_id", True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token_audience_association_table", "index")
    op.drop_column("membership_association_table", "index")
    op.drop_column("client_audience_association_table", "index")
    # ### end Alembic commands ###
