"""sqlalchemy association tables.

Revision ID: 1761860792
Revises: 1761851899
Create Date: 2025-10-30 22:46:32.173185

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from canaille.backends.sql.utils import is_mysql

# revision identifiers, used by Alembic.
revision: str = "1761860792"
down_revision: str | None = "1761851899"
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def fill_index(table, first, second, window):
    """Fill the NULL index values with the row number of each association."""
    if is_mysql(op.get_bind().dialect):
        op.execute(f"""
            UPDATE {table} t
            JOIN (
                SELECT {first}, {second}, ROW_NUMBER() OVER ({window}) - 1 as row_num
                FROM {table}
                WHERE `index` IS NULL
            ) s
            ON t.{first} = s.{first} AND t.{second} = s.{second}
            SET t.`index` = s.row_num;
        """)
        return

    op.execute(f"""
        UPDATE {table}
        SET "index" = s.row_num
        FROM (
            SELECT {first}, {second}, ROW_NUMBER() OVER ({window}) - 1 as row_num
            FROM {table}
            WHERE "index" IS NULL
        ) s
        WHERE {table}.{first} = s.{first}
          AND {table}.{second} = s.{second};
    """)


def upgrade() -> None:
    # Fill NULL index values before making columns NOT NULL
    fill_index(
        "client_audience_association_table",
        "audience_id",
        "client_id",
        "ORDER BY audience_id, client_id",
    )
    fill_index(
        "membership_association_table",
        "user_id",
        "group_id",
        "PARTITION BY group_id ORDER BY user_id",
    )
    fill_index(
        "token_audience_association_table",
        "token_id",
        "client_id",
        "ORDER BY token_id, client_id",
    )

    with op.batch_alter_table(
        "client_audience_association_table", schema=None
    ) as batch_op:
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("membership_association_table", schema=None) as batch_op:
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table(
        "token_audience_association_table", schema=None
    ) as batch_op:
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "token_audience_association_table", schema=None
    ) as batch_op:
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("membership_association_table", schema=None) as batch_op:
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table(
        "client_audience_association_table", schema=None
    ) as batch_op:
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
