"""add multiple owners for groups

Revision ID: 1765470639
Revises: 1761866414
Create Date: 2025-12-11 17:30:39.792279

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1765470639'
down_revision: str | None = '1761866414'
branch_labels: str | Sequence[str] | None = ()
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_ownership',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_ownership_group_id_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_group_ownership_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'group_id', name=op.f('pk_group_ownership'))
    )

    # Migrate existing owner_id data to the new association table
    op.execute("""
        INSERT INTO group_ownership (owner_id, group_id, created_at)
        SELECT owner_id, id, CURRENT_TIMESTAMP
        FROM "group"
        WHERE owner_id IS NOT NULL
    """)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_group_owner_id_user'), type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_group_owner_id_user'), 'user', ['owner_id'], ['id'])

    # Migrate data back (only first owner per group)
    op.execute("""
        UPDATE "group"
        SET owner_id = (
            SELECT owner_id
            FROM group_ownership
            WHERE group_ownership.group_id = "group".id
            ORDER BY created_at
            LIMIT 1
        )
    """)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_group_owner_id_user'), 'user', ['owner_id'], ['id'])

    op.drop_table('group_ownership')
    # ### end Alembic commands ###
