---
name: docker
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Get Canaille version
        id: version
        run: |
          CANAILLE_VERSION=$(uv run python -c "from importlib.metadata import version; print(version('canaille'))")
          echo "version=${CANAILLE_VERSION}" >> $GITHUB_OUTPUT
          echo "Canaille version: ${CANAILLE_VERSION}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            yaalcoop/canaille:latest
            yaalcoop/canaille:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
